spring:
  application:
    name: ditto

  profiles:
    default: local

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  config:
    import: classpath:/application-secret.yml

---

spring:
  config:
    activate:
      on-profile: local, dev, prod


springdoc:
  swagger-ui:
    path: /swagger-custom-ui.html
  api-docs:
    path: /api-docs

  default-consumes-media-type: application/json
  default-produces-media-type: application/json

  paths-to-match:
    - /api/**

  show-login-endpoint: true
