spring:
  application:
    name: ditto-dev

  datasource:
    url: jdbc:postgresql://postgres:5432/ditto

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
  
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://dev.ditto.pnu.app/api/login/oauth2/code/kakao

app:
  redirect:
    uri: https://dev.ditto.pnu.app

logging:
  level:
    org:
      springframework:
        web: debug
      hibernate:
        SQL: debug
        type: trace
