spring:
  application:
    name: ditto

  datasource:
    url: jdbc:postgresql://db.ditto.pnu.app:1004/ditto
    hikari:
      maximum-pool-size: 4
    username: ditto
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  config:
    import: classpath:/application-secret.yml

