spring:
  application:
    name: ditto

  datasource:
    url: jdbc:postgresql://db.ditto.pnu.app:1004/ditto
    hikari:
      maximum-pool-size: 4
    username: ditto
    password: kakao2024

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  config:
    import: classpath:/application-secret.yml

logging:
  level:
    org.apache.coyote.http11.Http11Processor: DEBUG


