spring:
  application:
    name: ditto

  datasource:
    url: jdbc:postgresql://postgres:5432/ditto

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: https://ditto.pnu.app/api/login/oauth2/code/kakao

app:
  redirect:
    uri: https://ditto-beta-eight.vercel.app

logging:
  level:
    org:
      springframework:
        web: info
      hibernate:
        SQL: info
        type: info
